language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - 5.1

before_script:
  - mysql -e 'create database rbac;'
  - mysql utravis --database rbac << sql/mysql.sql

install:
   - composer install

script: phpunit --configuration phpunit.xml --coverage-text