language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - mysql -e 'create database rbac;'
  - mysql -u travis rbac < sql/mysql.sql

install:
   - composer install

script: phpunit --configuration phpunit.xml --coverage-text